services:
  productapi:
    build: .
    container_name: productServer
    ports:
      - "3030:3030"
    depends_on:
      - db
    networks:
      - connector
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: productservice
      POSTGRES_USER: postgres
    networks:
      - connector
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
networks:
  connector:
volumes:
  pg_data:


